site_name: Für Demokratie! Wiesbadener Bürgerinnen und Bürger im Widerstand gegen die NS-Diktatur
use_directory_urls: false
theme:
    name: mkdocs
    custom_dir: 'custom_theme/'
extra_css:
    - css/background.css
plugins:
    - macros