site_name: Für Demokratie! Wiesbadener Bürgerinnen und Bürger im Widerstand gegen die NS-Diktatur
mobile_site_name: Für Demokratie!<br> Wiesbadener Bürgerinnen und Bürger im Widerstand gegen die NS-Diktatur
use_directory_urls: false
theme:
    name: mkdocs
    custom_dir: 'custom_theme/'
    nav_style: light
extra_css:
    - css/background.css
plugins:
    - macros
markdown_extensions:
  - attr_list
nav:
  - 'personen.md'
  - 'Personen':
     - Konrad Arndt:
        - personen/konrad-arndt/kurz.md
        - personen/konrad-arndt/lang.md
        - personen/konrad-arndt/zitate.md
        - personen/konrad-arndt/literatur.md
     - Ludwig Beck:
        - personen/ludwig-beck/kurz.md
        - personen/ludwig-beck/lang.md
        - personen/ludwig-beck/zitate.md
        - personen/ludwig-beck/literatur.md
     - Georg Buch:
        - personen/georg-buch/kurz.md
        - personen/georg-buch/lang.md
        - personen/georg-buch/zitate.md
        - personen/georg-buch/literatur.md
     -  Toni Sender:
        - personen/tony-sender/kurz.md
        - personen/tony-sender/lang.md
        - personen/tony-sender/zitate.md
        - personen/tony-sender/literatur.md
     - Fabian Schlaberndorff:
        - personen/fabian-schlaberndorff/kurz.md
        - personen/fabian-schlaberndorff/lang.md
        - personen/fabian-schlaberndorff/zitate.md
        - personen/fabian-schlaberndorff/literatur.md
     - Hermannn Kaiser:
        - personen/hermannn-kaiser/kurz.md
        - personen/hermannn-kaiser/lang.md
        - personen/hermannn-kaiser/zitate.md
        - personen/hermannn-kaiser/literatur.md
     - Heinrich Maschmeyer:
        - personen/heinrich_maschmeyer/kurz.md
        - personen/heinrich_maschmeyer/lang.md
        - personen/heinrich_maschmeyer/zitate.md
        - personen/heinrich_maschmeyer/literatur.md
     - Heinrich Roos:
        - personen/heinrich-roos/kurz.md
        - personen/heinrich-roos/lang.md
        - personen/heinrich-roos/zitate.md
        - personen/heinrich-roos/literatur.md
     - Hans Buttersack:
        - personen/hans-buttersack/kurz.md
        - personen/hans-buttersack/lang.md
        - personen/hans-buttersack/zitate.md
        - personen/hans-buttersack/literatur.md
     - Georg Feller:
        - personen/georg-feller/kurz.md
        - personen/georg-feller/lang.md
        - personen/georg-feller/zitate.md
        - personen/georg-feller/literatur.md
     - Henny Neu:
        - personen/henny-neu/kurz.md
        - personen/henny-neu/lang.md
        - personen/henny-neu/zitate.md
        - personen/henny-neu/literatur.md
     - Paul Krüger:
        - personen/paul-krüger/kurz.md
        - personen/paul-krüger/lang.md
        - personen/paul-krüger/zitate.md
        - personen/paul-krüger/literatur.md
     - Josef Leber:
        - personen/josef-leber/kurz.md
        - personen/josef-leber/lang.md
        - personen/josef-leber/zitate.md
        - personen/josef-leber/literatur.md
     - Johannes Maaß:
        - personen/johannes-maaß/kurz.md
        - personen/johannes-maaß/lang.md
        - personen/johannes-maaß/zitate.md
        - personen/johannes-maaß/literatur.md
  - 'Einleitung':  'einleitung/kurz.md'
  - 'Einleitung':
    - 'Einleitung Lang': einleitung/lang.md
    - 'Einleitung Kurz': einleitung/kurz.md
    - einleitung/zitate.md
    - 'Literaturhinweise': einleitung/literatur.md
  - 'projekt.md'
  - 'information.md'
  - 'impressum.md'