site_name: Für Demokratie! Wiesbadener Bürgerinnen und Bürger im Widerstand gegen die NS-Diktatur
mobile_site_name: Für Demokratie!<br> Wiesbadener Bürgerinnen und Bürger im Widerstand gegen die NS-Diktatur
use_directory_urls: false
theme:
    name: mkdocs
    custom_dir: 'custom_theme/'
    nav_style: light
extra_css:
    - css/background.css
plugins:
    - macros
markdown_extensions:
  - attr_list
nav:
  - 'personen.md'
  - 'Personen':
     - konrad-ardnt:
        - personen/konrad-arndt/zitate.md
        - personen/konrad-arndt/literatur.md
        - personen/konrad-arndt/kurz.md
        - personen/konrad-arndt/lang.md
     - ludwig-beck:
        - personen/ludwig-beck/zitate.md
        - personen/ludwig-beck/literatur.md
        - personen/ludwig-beck/kurz.md
        - personen/ludwig-beck/lang.md
     - georg-buch:
        - personen/georg-buch/zitate.md
        - personen/georg-buch/literatur.md
        - personen/georg-buch/kurz.md
        - personen/georg-buch/lang.md
     - tony-sender:
        - personen/tony-sender/zitate.md
        - personen/tony-sender/literatur.md
        - personen/tony-sender/kurz.md
        - personen/tony-sender/lang.md
     - fabian-schlaberndorff:
        - personen/fabian-schlaberndorff/zitate.md
        - personen/fabian-schlaberndorff/literatur.md
        - personen/fabian-schlaberndorff/kurz.md
        - personen/fabian-schlaberndorff/lang.md
     - hermannn-kaiser:
        - personen/hermannn-kaiser/zitate.md
        - personen/hermannn-kaiser/literatur.md
        - personen/hermannn-kaiser/kurz.md
        - personen/hermannn-kaiser/lang.md
     - heinrich_maschmeyer:
        - personen/heinrich_maschmeyer/zitate.md
        - personen/heinrich_maschmeyer/literatur.md
        - personen/heinrich_maschmeyer/kurz.md
        - personen/heinrich_maschmeyer/lang.md
     - heinrich-roos:
        - personen/heinrich-roos/zitate.md
        - personen/heinrich-roos/literatur.md
        - personen/heinrich-roos/kurz.md
        - personen/heinrich-roos/lang.md
     - hans-buttersack:
        - personen/hans-buttersack/zitate.md
        - personen/hans-buttersack/literatur.md
        - personen/hans-buttersack/kurz.md
        - personen/hans-buttersack/lang.md
     - georg-feller:
        - personen/georg-feller/zitate.md
        - personen/georg-feller/literatur.md
        - personen/georg-feller/kurz.md
        - personen/georg-feller/lang.md
     - henny-neu:
        - personen/henny-neu/zitate.md
        - personen/henny-neu/literatur.md
        - personen/henny-neu/kurz.md
        - personen/henny-neu/lang.md
     - paul-krüger:
        - personen/paul-krüger/zitate.md
        - personen/paul-krüger/literatur.md
        - personen/paul-krüger/kurz.md
        - personen/paul-krüger/lang.md
     - josef-leber:
        - personen/josef-leber/zitate.md
        - personen/josef-leber/literatur.md
        - personen/josef-leber/kurz.md
        - personen/josef-leber/lang.md
     - johannes-maaß:
        - personen/johannes-maaß/zitate.md
        - personen/johannes-maaß/literatur.md
        - personen/johannes-maaß/kurz.md
        - personen/johannes-maaß/lang.md
  - 'Einleitung':  'einleitung/kurz.md'
  - 'Einleitung':
    - 'Einleitung Lang': einleitung/lang.md
    - 'Einleitung Kurz': einleitung/kurz.md
    - einleitung/zitate.md
    - 'Literaturhinweise': einleitung/literatur.md
  - 'projekt.md'
  - 'information.md'
  - 'impressum.md'